--
-- PostgreSQL database dump
--

\restrict wSRmNlxcodpT6mYX9rVKGPA0jpYzLZBuFM1kS9FokUo9CrUz11P65xqtdjJNSge

-- Dumped from database version 15.17
-- Dumped by pg_dump version 15.17

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: posuser
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO posuser;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: posuser
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: posuser
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO posuser;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: posuser
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: posuser
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO posuser;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: posuser
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: catalogs_category; Type: TABLE; Schema: public; Owner: posuser
--

CREATE TABLE public.catalogs_category (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    image character varying(100),
    is_enabled boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    store_id bigint
);


ALTER TABLE public.catalogs_category OWNER TO posuser;

--
-- Name: catalogs_category_id_seq; Type: SEQUENCE; Schema: public; Owner: posuser
--

ALTER TABLE public.catalogs_category ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.catalogs_category_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: catalogs_item; Type: TABLE; Schema: public; Owner: posuser
--

CREATE TABLE public.catalogs_item (
    id bigint NOT NULL,
    code character varying(50),
    name character varying(255) NOT NULL,
    image character varying(100),
    description text,
    is_enabled boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    category_id bigint,
    price numeric(10,2) NOT NULL,
    store_id bigint
);


ALTER TABLE public.catalogs_item OWNER TO posuser;

--
-- Name: catalogs_item_id_seq; Type: SEQUENCE; Schema: public; Owner: posuser
--

ALTER TABLE public.catalogs_item ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.catalogs_item_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_taxconfiguration; Type: TABLE; Schema: public; Owner: posuser
--

CREATE TABLE public.core_taxconfiguration (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    tax_type character varying(20) NOT NULL,
    is_gst_enabled boolean NOT NULL,
    cgst_rate numeric(5,2) NOT NULL,
    sgst_rate numeric(5,2) NOT NULL,
    igst_rate numeric(5,2) NOT NULL,
    is_cess_enabled boolean NOT NULL,
    cess_rate numeric(5,2) NOT NULL,
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    store_id bigint
);


ALTER TABLE public.core_taxconfiguration OWNER TO posuser;

--
-- Name: core_taxconfiguration_id_seq; Type: SEQUENCE; Schema: public; Owner: posuser
--

ALTER TABLE public.core_taxconfiguration ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_taxconfiguration_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: posuser
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id bigint NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO posuser;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: posuser
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: posuser
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO posuser;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: posuser
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: posuser
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO posuser;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: posuser
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: posuser
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO posuser;

--
-- Name: restaurants_invoice; Type: TABLE; Schema: public; Owner: posuser
--

CREATE TABLE public.restaurants_invoice (
    id bigint NOT NULL,
    invoice_number character varying(50) NOT NULL,
    subtotal numeric(10,2) NOT NULL,
    tax_amount numeric(10,2) NOT NULL,
    tax_details jsonb NOT NULL,
    total_amount numeric(10,2) NOT NULL,
    payment_method character varying(20) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    order_id bigint NOT NULL,
    waiter_id bigint,
    store_id bigint
);


ALTER TABLE public.restaurants_invoice OWNER TO posuser;

--
-- Name: restaurants_invoice_id_seq; Type: SEQUENCE; Schema: public; Owner: posuser
--

ALTER TABLE public.restaurants_invoice ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.restaurants_invoice_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: restaurants_order; Type: TABLE; Schema: public; Owner: posuser
--

CREATE TABLE public.restaurants_order (
    id bigint NOT NULL,
    status character varying(20) NOT NULL,
    total_amount numeric(10,2) NOT NULL,
    notes text,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    table_id bigint,
    waiter_id bigint,
    order_type character varying(20) NOT NULL,
    store_id bigint,
    customer_mobile character varying(20),
    customer_name character varying(255),
    number_of_persons integer NOT NULL,
    CONSTRAINT restaurants_order_number_of_persons_check CHECK ((number_of_persons >= 0))
);


ALTER TABLE public.restaurants_order OWNER TO posuser;

--
-- Name: restaurants_order_id_seq; Type: SEQUENCE; Schema: public; Owner: posuser
--

ALTER TABLE public.restaurants_order ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.restaurants_order_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: restaurants_orderitem; Type: TABLE; Schema: public; Owner: posuser
--

CREATE TABLE public.restaurants_orderitem (
    id bigint NOT NULL,
    quantity integer NOT NULL,
    price numeric(10,2) NOT NULL,
    status character varying(20) NOT NULL,
    notes character varying(255),
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    item_id bigint NOT NULL,
    order_id bigint NOT NULL,
    rejection_note text,
    CONSTRAINT restaurants_orderitem_quantity_check CHECK ((quantity >= 0))
);


ALTER TABLE public.restaurants_orderitem OWNER TO posuser;

--
-- Name: restaurants_orderitem_id_seq; Type: SEQUENCE; Schema: public; Owner: posuser
--

ALTER TABLE public.restaurants_orderitem ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.restaurants_orderitem_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: restaurants_reservation; Type: TABLE; Schema: public; Owner: posuser
--

CREATE TABLE public.restaurants_reservation (
    id bigint NOT NULL,
    customer_name character varying(255) NOT NULL,
    customer_phone character varying(20) NOT NULL,
    reservation_time timestamp with time zone NOT NULL,
    number_of_guests integer NOT NULL,
    status character varying(20) NOT NULL,
    notes text,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    table_id bigint NOT NULL,
    store_id bigint,
    CONSTRAINT restaurants_reservation_number_of_guests_check CHECK ((number_of_guests >= 0))
);


ALTER TABLE public.restaurants_reservation OWNER TO posuser;

--
-- Name: restaurants_reservation_id_seq; Type: SEQUENCE; Schema: public; Owner: posuser
--

ALTER TABLE public.restaurants_reservation ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.restaurants_reservation_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: restaurants_table; Type: TABLE; Schema: public; Owner: posuser
--

CREATE TABLE public.restaurants_table (
    id bigint NOT NULL,
    number character varying(20) NOT NULL,
    capacity integer NOT NULL,
    status character varying(20) NOT NULL,
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    pos_x double precision NOT NULL,
    pos_y double precision NOT NULL,
    shape character varying(10) NOT NULL,
    store_id bigint,
    CONSTRAINT restaurants_table_capacity_check CHECK ((capacity >= 0))
);


ALTER TABLE public.restaurants_table OWNER TO posuser;

--
-- Name: restaurants_table_id_seq; Type: SEQUENCE; Schema: public; Owner: posuser
--

ALTER TABLE public.restaurants_table ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.restaurants_table_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: stores_store; Type: TABLE; Schema: public; Owner: posuser
--

CREATE TABLE public.stores_store (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    address text NOT NULL,
    phone character varying(20),
    email character varying(254),
    gst_number character varying(15),
    invoice_prefix character varying(10) DEFAULT 'INV'::character varying,
    logo character varying(100),
    is_active boolean DEFAULT true,
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    is_kitchen_step_enabled boolean DEFAULT true,
    is_take_away_enabled boolean DEFAULT true,
    is_reservations_enabled boolean DEFAULT true,
    thermal_printer_size character varying(10) DEFAULT '3_INCH'::character varying,
    fssai_lic_no character varying(50),
    location character varying(255),
    mobile character varying(20),
    thermal_printer_name character varying(255),
    thermal_printer_product_id character varying(20),
    thermal_printer_vendor_id character varying(20)
);


ALTER TABLE public.stores_store OWNER TO posuser;

--
-- Name: stores_store_id_seq; Type: SEQUENCE; Schema: public; Owner: posuser
--

ALTER TABLE public.stores_store ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.stores_store_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: token_blacklist_blacklistedtoken; Type: TABLE; Schema: public; Owner: posuser
--

CREATE TABLE public.token_blacklist_blacklistedtoken (
    id bigint NOT NULL,
    blacklisted_at timestamp with time zone NOT NULL,
    token_id bigint NOT NULL
);


ALTER TABLE public.token_blacklist_blacklistedtoken OWNER TO posuser;

--
-- Name: token_blacklist_blacklistedtoken_id_seq; Type: SEQUENCE; Schema: public; Owner: posuser
--

ALTER TABLE public.token_blacklist_blacklistedtoken ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.token_blacklist_blacklistedtoken_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: token_blacklist_outstandingtoken; Type: TABLE; Schema: public; Owner: posuser
--

CREATE TABLE public.token_blacklist_outstandingtoken (
    id bigint NOT NULL,
    token text NOT NULL,
    created_at timestamp with time zone,
    expires_at timestamp with time zone NOT NULL,
    user_id bigint,
    jti character varying(255) NOT NULL
);


ALTER TABLE public.token_blacklist_outstandingtoken OWNER TO posuser;

--
-- Name: token_blacklist_outstandingtoken_id_seq; Type: SEQUENCE; Schema: public; Owner: posuser
--

ALTER TABLE public.token_blacklist_outstandingtoken ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.token_blacklist_outstandingtoken_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_menupermission; Type: TABLE; Schema: public; Owner: posuser
--

CREATE TABLE public.users_menupermission (
    id bigint NOT NULL,
    group_id bigint,
    menu_key character varying(100) NOT NULL,
    is_enabled boolean DEFAULT true
);


ALTER TABLE public.users_menupermission OWNER TO posuser;

--
-- Name: users_menupermission_id_seq; Type: SEQUENCE; Schema: public; Owner: posuser
--

CREATE SEQUENCE public.users_menupermission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.users_menupermission_id_seq OWNER TO posuser;

--
-- Name: users_menupermission_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: posuser
--

ALTER SEQUENCE public.users_menupermission_id_seq OWNED BY public.users_menupermission.id;


--
-- Name: users_user; Type: TABLE; Schema: public; Owner: posuser
--

CREATE TABLE public.users_user (
    id bigint NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean DEFAULT false,
    username character varying(150) NOT NULL,
    first_name character varying(150),
    last_name character varying(150),
    email character varying(254),
    is_staff boolean DEFAULT false,
    is_active boolean DEFAULT true,
    date_joined timestamp with time zone DEFAULT now(),
    store_id bigint
);


ALTER TABLE public.users_user OWNER TO posuser;

--
-- Name: users_user_groups; Type: TABLE; Schema: public; Owner: posuser
--

CREATE TABLE public.users_user_groups (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.users_user_groups OWNER TO posuser;

--
-- Name: users_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: posuser
--

ALTER TABLE public.users_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_user_id_seq; Type: SEQUENCE; Schema: public; Owner: posuser
--

ALTER TABLE public.users_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_user_user_permissions; Type: TABLE; Schema: public; Owner: posuser
--

CREATE TABLE public.users_user_user_permissions (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.users_user_user_permissions OWNER TO posuser;

--
-- Name: users_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: posuser
--

ALTER TABLE public.users_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_menupermission id; Type: DEFAULT; Schema: public; Owner: posuser
--

ALTER TABLE ONLY public.users_menupermission ALTER COLUMN id SET DEFAULT nextval('public.users_menupermission_id_seq'::regclass);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: posuser
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: posuser
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: posuser
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: posuser
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: posuser
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: posuser
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: catalogs_category catalogs_category_name_store_id_e6198cb5_uniq; Type: CONSTRAINT; Schema: public; Owner: posuser
--

ALTER TABLE ONLY public.catalogs_category
    ADD CONSTRAINT catalogs_category_name_store_id_e6198cb5_uniq UNIQUE (name, store_id);


--
-- Name: catalogs_category catalogs_category_pkey; Type: CONSTRAINT; Schema: public; Owner: posuser
--

ALTER TABLE ONLY public.catalogs_category
    ADD CONSTRAINT catalogs_category_pkey PRIMARY KEY (id);


--
-- Name: catalogs_item catalogs_item_pkey; Type: CONSTRAINT; Schema: public; Owner: posuser
--

ALTER TABLE ONLY public.catalogs_item
    ADD CONSTRAINT catalogs_item_pkey PRIMARY KEY (id);


--
-- Name: core_taxconfiguration core_taxconfiguration_pkey; Type: CONSTRAINT; Schema: public; Owner: posuser
--

ALTER TABLE ONLY public.core_taxconfiguration
    ADD CONSTRAINT core_taxconfiguration_pkey PRIMARY KEY (id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: posuser
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: posuser
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: posuser
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: posuser
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: posuser
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: restaurants_invoice restaurants_invoice_invoice_number_key; Type: CONSTRAINT; Schema: public; Owner: posuser
--

ALTER TABLE ONLY public.restaurants_invoice
    ADD CONSTRAINT restaurants_invoice_invoice_number_key UNIQUE (invoice_number);


--
-- Name: restaurants_invoice restaurants_invoice_order_id_key; Type: CONSTRAINT; Schema: public; Owner: posuser
--

ALTER TABLE ONLY public.restaurants_invoice
    ADD CONSTRAINT restaurants_invoice_order_id_key UNIQUE (order_id);


--
-- Name: restaurants_invoice restaurants_invoice_pkey; Type: CONSTRAINT; Schema: public; Owner: posuser
--

ALTER TABLE ONLY public.restaurants_invoice
    ADD CONSTRAINT restaurants_invoice_pkey PRIMARY KEY (id);


--
-- Name: restaurants_order restaurants_order_pkey; Type: CONSTRAINT; Schema: public; Owner: posuser
--

ALTER TABLE ONLY public.restaurants_order
    ADD CONSTRAINT restaurants_order_pkey PRIMARY KEY (id);


--
-- Name: restaurants_orderitem restaurants_orderitem_pkey; Type: CONSTRAINT; Schema: public; Owner: posuser
--

ALTER TABLE ONLY public.restaurants_orderitem
    ADD CONSTRAINT restaurants_orderitem_pkey PRIMARY KEY (id);


--
-- Name: restaurants_reservation restaurants_reservation_pkey; Type: CONSTRAINT; Schema: public; Owner: posuser
--

ALTER TABLE ONLY public.restaurants_reservation
    ADD CONSTRAINT restaurants_reservation_pkey PRIMARY KEY (id);


--
-- Name: restaurants_table restaurants_table_number_store_id_067d6c21_uniq; Type: CONSTRAINT; Schema: public; Owner: posuser
--

ALTER TABLE ONLY public.restaurants_table
    ADD CONSTRAINT restaurants_table_number_store_id_067d6c21_uniq UNIQUE (number, store_id);


--
-- Name: restaurants_table restaurants_table_pkey; Type: CONSTRAINT; Schema: public; Owner: posuser
--

ALTER TABLE ONLY public.restaurants_table
    ADD CONSTRAINT restaurants_table_pkey PRIMARY KEY (id);


--
-- Name: stores_store stores_store_pkey; Type: CONSTRAINT; Schema: public; Owner: posuser
--

ALTER TABLE ONLY public.stores_store
    ADD CONSTRAINT stores_store_pkey PRIMARY KEY (id);


--
-- Name: token_blacklist_blacklistedtoken token_blacklist_blacklistedtoken_pkey; Type: CONSTRAINT; Schema: public; Owner: posuser
--

ALTER TABLE ONLY public.token_blacklist_blacklistedtoken
    ADD CONSTRAINT token_blacklist_blacklistedtoken_pkey PRIMARY KEY (id);


--
-- Name: token_blacklist_blacklistedtoken token_blacklist_blacklistedtoken_token_id_key; Type: CONSTRAINT; Schema: public; Owner: posuser
--

ALTER TABLE ONLY public.token_blacklist_blacklistedtoken
    ADD CONSTRAINT token_blacklist_blacklistedtoken_token_id_key UNIQUE (token_id);


--
-- Name: token_blacklist_outstandingtoken token_blacklist_outstandingtoken_jti_hex_d9bdf6f7_uniq; Type: CONSTRAINT; Schema: public; Owner: posuser
--

ALTER TABLE ONLY public.token_blacklist_outstandingtoken
    ADD CONSTRAINT token_blacklist_outstandingtoken_jti_hex_d9bdf6f7_uniq UNIQUE (jti);


--
-- Name: token_blacklist_outstandingtoken token_blacklist_outstandingtoken_pkey; Type: CONSTRAINT; Schema: public; Owner: posuser
--

ALTER TABLE ONLY public.token_blacklist_outstandingtoken
    ADD CONSTRAINT token_blacklist_outstandingtoken_pkey PRIMARY KEY (id);


--
-- Name: users_menupermission users_menupermission_pkey; Type: CONSTRAINT; Schema: public; Owner: posuser
--

ALTER TABLE ONLY public.users_menupermission
    ADD CONSTRAINT users_menupermission_pkey PRIMARY KEY (id);


--
-- Name: users_user_groups users_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: posuser
--

ALTER TABLE ONLY public.users_user_groups
    ADD CONSTRAINT users_user_groups_pkey PRIMARY KEY (id);


--
-- Name: users_user_groups users_user_groups_user_id_group_id_b88eab82_uniq; Type: CONSTRAINT; Schema: public; Owner: posuser
--

ALTER TABLE ONLY public.users_user_groups
    ADD CONSTRAINT users_user_groups_user_id_group_id_b88eab82_uniq UNIQUE (user_id, group_id);


--
-- Name: users_user users_user_pkey; Type: CONSTRAINT; Schema: public; Owner: posuser
--

ALTER TABLE ONLY public.users_user
    ADD CONSTRAINT users_user_pkey PRIMARY KEY (id);


--
-- Name: users_user_user_permissions users_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: posuser
--

ALTER TABLE ONLY public.users_user_user_permissions
    ADD CONSTRAINT users_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: users_user_user_permissions users_user_user_permissions_user_id_permission_id_43338c45_uniq; Type: CONSTRAINT; Schema: public; Owner: posuser
--

ALTER TABLE ONLY public.users_user_user_permissions
    ADD CONSTRAINT users_user_user_permissions_user_id_permission_id_43338c45_uniq UNIQUE (user_id, permission_id);


--
-- Name: users_user users_user_username_key; Type: CONSTRAINT; Schema: public; Owner: posuser
--

ALTER TABLE ONLY public.users_user
    ADD CONSTRAINT users_user_username_key UNIQUE (username);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: posuser
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: posuser
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: posuser
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: posuser
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: catalogs_category_store_id_242dc9f7; Type: INDEX; Schema: public; Owner: posuser
--

CREATE INDEX catalogs_category_store_id_242dc9f7 ON public.catalogs_category USING btree (store_id);


--
-- Name: catalogs_item_category_id_2a0b34c4; Type: INDEX; Schema: public; Owner: posuser
--

CREATE INDEX catalogs_item_category_id_2a0b34c4 ON public.catalogs_item USING btree (category_id);


--
-- Name: catalogs_item_store_id_77ee901a; Type: INDEX; Schema: public; Owner: posuser
--

CREATE INDEX catalogs_item_store_id_77ee901a ON public.catalogs_item USING btree (store_id);


--
-- Name: core_taxconfiguration_store_id_e9084b69; Type: INDEX; Schema: public; Owner: posuser
--

CREATE INDEX core_taxconfiguration_store_id_e9084b69 ON public.core_taxconfiguration USING btree (store_id);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: posuser
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: posuser
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: posuser
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: posuser
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: restaurants_invoice_invoice_number_fcf6d5ac_like; Type: INDEX; Schema: public; Owner: posuser
--

CREATE INDEX restaurants_invoice_invoice_number_fcf6d5ac_like ON public.restaurants_invoice USING btree (invoice_number varchar_pattern_ops);


--
-- Name: restaurants_invoice_store_id_68c581ed; Type: INDEX; Schema: public; Owner: posuser
--

CREATE INDEX restaurants_invoice_store_id_68c581ed ON public.restaurants_invoice USING btree (store_id);


--
-- Name: restaurants_invoice_waiter_id_73dc2f8b; Type: INDEX; Schema: public; Owner: posuser
--

CREATE INDEX restaurants_invoice_waiter_id_73dc2f8b ON public.restaurants_invoice USING btree (waiter_id);


--
-- Name: restaurants_order_store_id_da05b0d0; Type: INDEX; Schema: public; Owner: posuser
--

CREATE INDEX restaurants_order_store_id_da05b0d0 ON public.restaurants_order USING btree (store_id);


--
-- Name: restaurants_order_table_id_4f04293f; Type: INDEX; Schema: public; Owner: posuser
--

CREATE INDEX restaurants_order_table_id_4f04293f ON public.restaurants_order USING btree (table_id);


--
-- Name: restaurants_order_waiter_id_ea3b81ed; Type: INDEX; Schema: public; Owner: posuser
--

CREATE INDEX restaurants_order_waiter_id_ea3b81ed ON public.restaurants_order USING btree (waiter_id);


--
-- Name: restaurants_orderitem_item_id_f09ca042; Type: INDEX; Schema: public; Owner: posuser
--

CREATE INDEX restaurants_orderitem_item_id_f09ca042 ON public.restaurants_orderitem USING btree (item_id);


--
-- Name: restaurants_orderitem_order_id_4d09be07; Type: INDEX; Schema: public; Owner: posuser
--

CREATE INDEX restaurants_orderitem_order_id_4d09be07 ON public.restaurants_orderitem USING btree (order_id);


--
-- Name: restaurants_reservation_store_id_98838127; Type: INDEX; Schema: public; Owner: posuser
--

CREATE INDEX restaurants_reservation_store_id_98838127 ON public.restaurants_reservation USING btree (store_id);


--
-- Name: restaurants_reservation_table_id_2ac0dd3f; Type: INDEX; Schema: public; Owner: posuser
--

CREATE INDEX restaurants_reservation_table_id_2ac0dd3f ON public.restaurants_reservation USING btree (table_id);


--
-- Name: restaurants_table_store_id_1dffb930; Type: INDEX; Schema: public; Owner: posuser
--

CREATE INDEX restaurants_table_store_id_1dffb930 ON public.restaurants_table USING btree (store_id);


--
-- Name: token_blacklist_outstandingtoken_jti_hex_d9bdf6f7_like; Type: INDEX; Schema: public; Owner: posuser
--

CREATE INDEX token_blacklist_outstandingtoken_jti_hex_d9bdf6f7_like ON public.token_blacklist_outstandingtoken USING btree (jti varchar_pattern_ops);


--
-- Name: token_blacklist_outstandingtoken_user_id_83bc629a; Type: INDEX; Schema: public; Owner: posuser
--

CREATE INDEX token_blacklist_outstandingtoken_user_id_83bc629a ON public.token_blacklist_outstandingtoken USING btree (user_id);


--
-- Name: users_user_groups_group_id_9afc8d0e; Type: INDEX; Schema: public; Owner: posuser
--

CREATE INDEX users_user_groups_group_id_9afc8d0e ON public.users_user_groups USING btree (group_id);


--
-- Name: users_user_groups_user_id_5f6f5a90; Type: INDEX; Schema: public; Owner: posuser
--

CREATE INDEX users_user_groups_user_id_5f6f5a90 ON public.users_user_groups USING btree (user_id);


--
-- Name: users_user_store_id_41009bb0; Type: INDEX; Schema: public; Owner: posuser
--

CREATE INDEX users_user_store_id_41009bb0 ON public.users_user USING btree (store_id);


--
-- Name: users_user_user_permissions_permission_id_0b93982e; Type: INDEX; Schema: public; Owner: posuser
--

CREATE INDEX users_user_user_permissions_permission_id_0b93982e ON public.users_user_user_permissions USING btree (permission_id);


--
-- Name: users_user_user_permissions_user_id_20aca447; Type: INDEX; Schema: public; Owner: posuser
--

CREATE INDEX users_user_user_permissions_user_id_20aca447 ON public.users_user_user_permissions USING btree (user_id);


--
-- Name: users_user_username_06e46fe6_like; Type: INDEX; Schema: public; Owner: posuser
--

CREATE INDEX users_user_username_06e46fe6_like ON public.users_user USING btree (username varchar_pattern_ops);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: posuser
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: posuser
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: posuser
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: catalogs_category catalogs_category_store_id_242dc9f7_fk_stores_store_id; Type: FK CONSTRAINT; Schema: public; Owner: posuser
--

ALTER TABLE ONLY public.catalogs_category
    ADD CONSTRAINT catalogs_category_store_id_242dc9f7_fk_stores_store_id FOREIGN KEY (store_id) REFERENCES public.stores_store(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: catalogs_item catalogs_item_category_id_2a0b34c4_fk_catalogs_category_id; Type: FK CONSTRAINT; Schema: public; Owner: posuser
--

ALTER TABLE ONLY public.catalogs_item
    ADD CONSTRAINT catalogs_item_category_id_2a0b34c4_fk_catalogs_category_id FOREIGN KEY (category_id) REFERENCES public.catalogs_category(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: catalogs_item catalogs_item_store_id_77ee901a_fk_stores_store_id; Type: FK CONSTRAINT; Schema: public; Owner: posuser
--

ALTER TABLE ONLY public.catalogs_item
    ADD CONSTRAINT catalogs_item_store_id_77ee901a_fk_stores_store_id FOREIGN KEY (store_id) REFERENCES public.stores_store(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_taxconfiguration core_taxconfiguration_store_id_e9084b69_fk_stores_store_id; Type: FK CONSTRAINT; Schema: public; Owner: posuser
--

ALTER TABLE ONLY public.core_taxconfiguration
    ADD CONSTRAINT core_taxconfiguration_store_id_e9084b69_fk_stores_store_id FOREIGN KEY (store_id) REFERENCES public.stores_store(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: posuser
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: posuser
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_users_user_id FOREIGN KEY (user_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_menupermission fk_users_menupermission_group; Type: FK CONSTRAINT; Schema: public; Owner: posuser
--

ALTER TABLE ONLY public.users_menupermission
    ADD CONSTRAINT fk_users_menupermission_group FOREIGN KEY (group_id) REFERENCES public.auth_group(id);


--
-- Name: users_user_groups fk_users_user_groups_group; Type: FK CONSTRAINT; Schema: public; Owner: posuser
--

ALTER TABLE ONLY public.users_user_groups
    ADD CONSTRAINT fk_users_user_groups_group FOREIGN KEY (group_id) REFERENCES public.auth_group(id);


--
-- Name: users_user_groups fk_users_user_groups_user; Type: FK CONSTRAINT; Schema: public; Owner: posuser
--

ALTER TABLE ONLY public.users_user_groups
    ADD CONSTRAINT fk_users_user_groups_user FOREIGN KEY (user_id) REFERENCES public.users_user(id);


--
-- Name: users_user fk_users_user_store; Type: FK CONSTRAINT; Schema: public; Owner: posuser
--

ALTER TABLE ONLY public.users_user
    ADD CONSTRAINT fk_users_user_store FOREIGN KEY (store_id) REFERENCES public.stores_store(id);


--
-- Name: restaurants_invoice restaurants_invoice_order_id_fcff7340_fk_restaurants_order_id; Type: FK CONSTRAINT; Schema: public; Owner: posuser
--

ALTER TABLE ONLY public.restaurants_invoice
    ADD CONSTRAINT restaurants_invoice_order_id_fcff7340_fk_restaurants_order_id FOREIGN KEY (order_id) REFERENCES public.restaurants_order(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: restaurants_invoice restaurants_invoice_store_id_68c581ed_fk_stores_store_id; Type: FK CONSTRAINT; Schema: public; Owner: posuser
--

ALTER TABLE ONLY public.restaurants_invoice
    ADD CONSTRAINT restaurants_invoice_store_id_68c581ed_fk_stores_store_id FOREIGN KEY (store_id) REFERENCES public.stores_store(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: restaurants_invoice restaurants_invoice_waiter_id_73dc2f8b_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: posuser
--

ALTER TABLE ONLY public.restaurants_invoice
    ADD CONSTRAINT restaurants_invoice_waiter_id_73dc2f8b_fk_users_user_id FOREIGN KEY (waiter_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: restaurants_order restaurants_order_store_id_da05b0d0_fk_stores_store_id; Type: FK CONSTRAINT; Schema: public; Owner: posuser
--

ALTER TABLE ONLY public.restaurants_order
    ADD CONSTRAINT restaurants_order_store_id_da05b0d0_fk_stores_store_id FOREIGN KEY (store_id) REFERENCES public.stores_store(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: restaurants_order restaurants_order_table_id_4f04293f_fk_restaurants_table_id; Type: FK CONSTRAINT; Schema: public; Owner: posuser
--

ALTER TABLE ONLY public.restaurants_order
    ADD CONSTRAINT restaurants_order_table_id_4f04293f_fk_restaurants_table_id FOREIGN KEY (table_id) REFERENCES public.restaurants_table(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: restaurants_order restaurants_order_waiter_id_ea3b81ed_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: posuser
--

ALTER TABLE ONLY public.restaurants_order
    ADD CONSTRAINT restaurants_order_waiter_id_ea3b81ed_fk_users_user_id FOREIGN KEY (waiter_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: restaurants_orderitem restaurants_orderitem_item_id_f09ca042_fk_catalogs_item_id; Type: FK CONSTRAINT; Schema: public; Owner: posuser
--

ALTER TABLE ONLY public.restaurants_orderitem
    ADD CONSTRAINT restaurants_orderitem_item_id_f09ca042_fk_catalogs_item_id FOREIGN KEY (item_id) REFERENCES public.catalogs_item(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: restaurants_orderitem restaurants_orderitem_order_id_4d09be07_fk_restaurants_order_id; Type: FK CONSTRAINT; Schema: public; Owner: posuser
--

ALTER TABLE ONLY public.restaurants_orderitem
    ADD CONSTRAINT restaurants_orderitem_order_id_4d09be07_fk_restaurants_order_id FOREIGN KEY (order_id) REFERENCES public.restaurants_order(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: restaurants_reservation restaurants_reservat_table_id_2ac0dd3f_fk_restauran; Type: FK CONSTRAINT; Schema: public; Owner: posuser
--

ALTER TABLE ONLY public.restaurants_reservation
    ADD CONSTRAINT restaurants_reservat_table_id_2ac0dd3f_fk_restauran FOREIGN KEY (table_id) REFERENCES public.restaurants_table(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: restaurants_reservation restaurants_reservation_store_id_98838127_fk_stores_store_id; Type: FK CONSTRAINT; Schema: public; Owner: posuser
--

ALTER TABLE ONLY public.restaurants_reservation
    ADD CONSTRAINT restaurants_reservation_store_id_98838127_fk_stores_store_id FOREIGN KEY (store_id) REFERENCES public.stores_store(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: restaurants_table restaurants_table_store_id_1dffb930_fk_stores_store_id; Type: FK CONSTRAINT; Schema: public; Owner: posuser
--

ALTER TABLE ONLY public.restaurants_table
    ADD CONSTRAINT restaurants_table_store_id_1dffb930_fk_stores_store_id FOREIGN KEY (store_id) REFERENCES public.stores_store(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: token_blacklist_blacklistedtoken token_blacklist_blacklistedtoken_token_id_3cc7fe56_fk; Type: FK CONSTRAINT; Schema: public; Owner: posuser
--

ALTER TABLE ONLY public.token_blacklist_blacklistedtoken
    ADD CONSTRAINT token_blacklist_blacklistedtoken_token_id_3cc7fe56_fk FOREIGN KEY (token_id) REFERENCES public.token_blacklist_outstandingtoken(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: token_blacklist_outstandingtoken token_blacklist_outs_user_id_83bc629a_fk_users_use; Type: FK CONSTRAINT; Schema: public; Owner: posuser
--

ALTER TABLE ONLY public.token_blacklist_outstandingtoken
    ADD CONSTRAINT token_blacklist_outs_user_id_83bc629a_fk_users_use FOREIGN KEY (user_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_user_groups users_user_groups_group_id_9afc8d0e_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: posuser
--

ALTER TABLE ONLY public.users_user_groups
    ADD CONSTRAINT users_user_groups_group_id_9afc8d0e_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_user_groups users_user_groups_user_id_5f6f5a90_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: posuser
--

ALTER TABLE ONLY public.users_user_groups
    ADD CONSTRAINT users_user_groups_user_id_5f6f5a90_fk_users_user_id FOREIGN KEY (user_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_user users_user_store_id_41009bb0_fk_stores_store_id; Type: FK CONSTRAINT; Schema: public; Owner: posuser
--

ALTER TABLE ONLY public.users_user
    ADD CONSTRAINT users_user_store_id_41009bb0_fk_stores_store_id FOREIGN KEY (store_id) REFERENCES public.stores_store(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_user_user_permissions users_user_user_perm_permission_id_0b93982e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: posuser
--

ALTER TABLE ONLY public.users_user_user_permissions
    ADD CONSTRAINT users_user_user_perm_permission_id_0b93982e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_user_user_permissions users_user_user_permissions_user_id_20aca447_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: posuser
--

ALTER TABLE ONLY public.users_user_user_permissions
    ADD CONSTRAINT users_user_user_permissions_user_id_20aca447_fk_users_user_id FOREIGN KEY (user_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

\unrestrict wSRmNlxcodpT6mYX9rVKGPA0jpYzLZBuFM1kS9FokUo9CrUz11P65xqtdjJNSge

--
-- PostgreSQL database dump
--

\restrict XgEgqa9zdS744SO6fMnUCNEUhZOoEPg6njKSqvrwVbYcp1Z8uRAezwKtjrDfqLb

-- Dumped from database version 15.17
-- Dumped by pg_dump version 15.17

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: posuser
--

INSERT INTO public.auth_group (id, name) VALUES (1, 'SUPER_ADMIN');


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: posuser
--

INSERT INTO public.django_content_type (id, app_label, model) VALUES (1, 'admin', 'logentry');
INSERT INTO public.django_content_type (id, app_label, model) VALUES (2, 'auth', 'permission');
INSERT INTO public.django_content_type (id, app_label, model) VALUES (3, 'auth', 'group');
INSERT INTO public.django_content_type (id, app_label, model) VALUES (4, 'contenttypes', 'contenttype');
INSERT INTO public.django_content_type (id, app_label, model) VALUES (5, 'sessions', 'session');
INSERT INTO public.django_content_type (id, app_label, model) VALUES (6, 'token_blacklist', 'blacklistedtoken');
INSERT INTO public.django_content_type (id, app_label, model) VALUES (7, 'token_blacklist', 'outstandingtoken');
INSERT INTO public.django_content_type (id, app_label, model) VALUES (8, 'users', 'user');
INSERT INTO public.django_content_type (id, app_label, model) VALUES (9, 'catalogs', 'category');
INSERT INTO public.django_content_type (id, app_label, model) VALUES (10, 'catalogs', 'item');
INSERT INTO public.django_content_type (id, app_label, model) VALUES (11, 'restaurants', 'order');
INSERT INTO public.django_content_type (id, app_label, model) VALUES (12, 'restaurants', 'table');
INSERT INTO public.django_content_type (id, app_label, model) VALUES (13, 'restaurants', 'reservation');
INSERT INTO public.django_content_type (id, app_label, model) VALUES (14, 'restaurants', 'orderitem');
INSERT INTO public.django_content_type (id, app_label, model) VALUES (15, 'restaurants', 'invoice');
INSERT INTO public.django_content_type (id, app_label, model) VALUES (16, 'core', 'taxconfiguration');
INSERT INTO public.django_content_type (id, app_label, model) VALUES (17, 'stores', 'store');


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: posuser
--

INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (1, 'Can add log entry', 1, 'add_logentry');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (2, 'Can change log entry', 1, 'change_logentry');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (3, 'Can delete log entry', 1, 'delete_logentry');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (4, 'Can view log entry', 1, 'view_logentry');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (5, 'Can add permission', 2, 'add_permission');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (6, 'Can change permission', 2, 'change_permission');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (7, 'Can delete permission', 2, 'delete_permission');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (8, 'Can view permission', 2, 'view_permission');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (9, 'Can add group', 3, 'add_group');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (10, 'Can change group', 3, 'change_group');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (11, 'Can delete group', 3, 'delete_group');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (12, 'Can view group', 3, 'view_group');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (13, 'Can add content type', 4, 'add_contenttype');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (14, 'Can change content type', 4, 'change_contenttype');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (15, 'Can delete content type', 4, 'delete_contenttype');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (16, 'Can view content type', 4, 'view_contenttype');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (17, 'Can add session', 5, 'add_session');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (18, 'Can change session', 5, 'change_session');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (19, 'Can delete session', 5, 'delete_session');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (20, 'Can view session', 5, 'view_session');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (21, 'Can add Blacklisted Token', 6, 'add_blacklistedtoken');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (22, 'Can change Blacklisted Token', 6, 'change_blacklistedtoken');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (23, 'Can delete Blacklisted Token', 6, 'delete_blacklistedtoken');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (24, 'Can view Blacklisted Token', 6, 'view_blacklistedtoken');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (25, 'Can add Outstanding Token', 7, 'add_outstandingtoken');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (26, 'Can change Outstanding Token', 7, 'change_outstandingtoken');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (27, 'Can delete Outstanding Token', 7, 'delete_outstandingtoken');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (28, 'Can view Outstanding Token', 7, 'view_outstandingtoken');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (29, 'Can add user', 8, 'add_user');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (30, 'Can change user', 8, 'change_user');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (31, 'Can delete user', 8, 'delete_user');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (32, 'Can view user', 8, 'view_user');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (33, 'Can add new users to the system', 8, 'can_add_users');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (34, 'Can manage table layout', 8, 'manage_table_layout_access');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (35, 'Can view table layout', 8, 'view_table_layout_access');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (36, 'Can update table status', 8, 'access_to_update_table_status');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (37, 'Can take restaurant orders', 8, 'access_to_take_order');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (38, 'Can view kitchen display', 8, 'access_to_view_kitchen_display');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (39, 'Can manage kitchen queue', 8, 'access_to_manage_kitchen_queue');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (40, 'Can manage payment and billing', 8, 'access_to_payment_management');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (41, 'Can delete orders', 8, 'access_to_delete_order');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (42, 'Can view analytics and reports', 8, 'view_reports');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (43, 'Can view dashboard', 8, 'access_to_dashboard');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (44, 'Can add category', 9, 'add_category');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (45, 'Can change category', 9, 'change_category');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (46, 'Can delete category', 9, 'delete_category');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (47, 'Can view category', 9, 'view_category');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (48, 'Can add item', 10, 'add_item');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (49, 'Can change item', 10, 'change_item');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (50, 'Can delete item', 10, 'delete_item');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (51, 'Can view item', 10, 'view_item');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (52, 'Can add order', 11, 'add_order');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (53, 'Can change order', 11, 'change_order');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (54, 'Can delete order', 11, 'delete_order');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (55, 'Can view order', 11, 'view_order');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (56, 'Can add table', 12, 'add_table');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (57, 'Can change table', 12, 'change_table');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (58, 'Can delete table', 12, 'delete_table');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (59, 'Can view table', 12, 'view_table');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (60, 'Can add reservation', 13, 'add_reservation');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (61, 'Can change reservation', 13, 'change_reservation');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (62, 'Can delete reservation', 13, 'delete_reservation');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (63, 'Can view reservation', 13, 'view_reservation');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (64, 'Can add order item', 14, 'add_orderitem');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (65, 'Can change order item', 14, 'change_orderitem');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (66, 'Can delete order item', 14, 'delete_orderitem');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (67, 'Can view order item', 14, 'view_orderitem');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (68, 'Can add invoice', 15, 'add_invoice');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (69, 'Can change invoice', 15, 'change_invoice');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (70, 'Can delete invoice', 15, 'delete_invoice');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (71, 'Can view invoice', 15, 'view_invoice');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (72, 'Can add Tax Configuration', 16, 'add_taxconfiguration');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (73, 'Can change Tax Configuration', 16, 'change_taxconfiguration');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (74, 'Can delete Tax Configuration', 16, 'delete_taxconfiguration');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (75, 'Can view Tax Configuration', 16, 'view_taxconfiguration');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (76, 'Can add store', 17, 'add_store');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (77, 'Can change store', 17, 'change_store');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (78, 'Can delete store', 17, 'delete_store');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (79, 'Can view store', 17, 'view_store');


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: posuser
--



--
-- Data for Name: stores_store; Type: TABLE DATA; Schema: public; Owner: posuser
--

INSERT INTO public.stores_store (id, name, address, phone, email, gst_number, invoice_prefix, logo, is_active, created_at, updated_at, is_kitchen_step_enabled, is_take_away_enabled, is_reservations_enabled, thermal_printer_size, fssai_lic_no, location, mobile, thermal_printer_name, thermal_printer_product_id, thermal_printer_vendor_id) VALUES (2, 'Second Branch', 'Second Branch street, second city', '', 'secondstore@mario.com', '11AAA3482CD299', 'INV2', '', true, '2026-04-29 14:45:09.055379+00', '2026-04-29 14:45:09.055405+00', true, true, true, '3_INCH', '111232322423341114', '', '2222222222', NULL, NULL, NULL);
INSERT INTO public.stores_store (id, name, address, phone, email, gst_number, invoice_prefix, logo, is_active, created_at, updated_at, is_kitchen_step_enabled, is_take_away_enabled, is_reservations_enabled, thermal_printer_size, fssai_lic_no, location, mobile, thermal_printer_name, thermal_printer_product_id, thermal_printer_vendor_id) VALUES (1, 'MARIO JUICY - Main', 'Puthur, Coimbatore', '', 'mainstore@mario.com', '222AAA2332UX232', 'INV1', '', true, '2026-04-29 11:54:18.83755+00', '2026-04-29 19:40:15.751615+00', false, true, false, '3_INCH', '3232112232132', '', '1111111111', 'USB Device 0fe6:811e', '0x811e', '0x0fe6');


--
-- Data for Name: core_taxconfiguration; Type: TABLE DATA; Schema: public; Owner: posuser
--

INSERT INTO public.core_taxconfiguration (id, name, tax_type, is_gst_enabled, cgst_rate, sgst_rate, igst_rate, is_cess_enabled, cess_rate, is_active, created_at, updated_at, store_id) VALUES (1, 'Default Tax Configuration', 'EXCLUSIVE', false, 0.00, 0.00, 0.00, false, 0.00, true, '2026-04-29 13:58:44.955012+00', '2026-04-29 13:58:44.955024+00', 1);


--
-- Data for Name: users_menupermission; Type: TABLE DATA; Schema: public; Owner: posuser
--



--
-- Data for Name: users_user; Type: TABLE DATA; Schema: public; Owner: posuser
--

INSERT INTO public.users_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, store_id) VALUES (1, 'pbkdf2_sha256$600000$ayst5qhXvr6E7Nal7O81S5$aLb+OZJe64T3383hNi0S+uJAPTFPl2THBpw3hg0s3+s=', NULL, true, 'admin', '', '', 'admin@mario.com', true, true, '2026-04-29 13:40:01.052318+00', NULL);


--
-- Data for Name: users_user_groups; Type: TABLE DATA; Schema: public; Owner: posuser
--

INSERT INTO public.users_user_groups (id, user_id, group_id) VALUES (1, 1, 1);


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: posuser
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, true);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: posuser
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: posuser
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 79, true);


--
-- Name: core_taxconfiguration_id_seq; Type: SEQUENCE SET; Schema: public; Owner: posuser
--

SELECT pg_catalog.setval('public.core_taxconfiguration_id_seq', 1, true);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: posuser
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 17, true);


--
-- Name: stores_store_id_seq; Type: SEQUENCE SET; Schema: public; Owner: posuser
--

SELECT pg_catalog.setval('public.stores_store_id_seq', 2, true);


--
-- Name: users_menupermission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: posuser
--

SELECT pg_catalog.setval('public.users_menupermission_id_seq', 1, false);


--
-- Name: users_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: posuser
--

SELECT pg_catalog.setval('public.users_user_groups_id_seq', 1, true);


--
-- Name: users_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: posuser
--

SELECT pg_catalog.setval('public.users_user_id_seq', 1, true);


--
-- PostgreSQL database dump complete
--

\unrestrict XgEgqa9zdS744SO6fMnUCNEUhZOoEPg6njKSqvrwVbYcp1Z8uRAezwKtjrDfqLb

