# Generated by Django 4.2.27 on 2026-04-10 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('ORDER_TAKEN', 'Order Taken'), ('AWAITING', 'Awaiting'), ('PREPARING', 'Preparing'), ('PREPARED', 'Prepared'), ('SERVED', 'Served'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], default='ORDER_TAKEN', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('ORDERED', 'Ordered'), ('PREPARING', 'Preparing'), ('READY', 'Ready'), ('SERVED', 'Served'), ('CANCELLED', 'Cancelled')], default='ORDERED', max_length=20),
        ),
    ]
