# Generated by Django 4.2.27 on 2026-04-10 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_alter_order_status_alter_orderitem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='pos_x',
            field=models.FloatField(default=10.0),
        ),
        migrations.AddField(
            model_name='table',
            name='pos_y',
            field=models.FloatField(default=10.0),
        ),
        migrations.AddField(
            model_name='table',
            name='shape',
            field=models.CharField(choices=[('RECT', 'Rectangle'), ('ROUND', 'Round')], default='RECT', max_length=10),
        ),
    ]
