# Generated by Django 4.2.27 on 2026-04-11 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_alter_order_status_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('DINE_IN', 'Dine-in'), ('TAKE_AWAY', 'Take-away')], default='DINE_IN', max_length=20),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='rejection_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('ORDER_TAKEN', 'Order Taken'), ('AWAITING', 'Awaiting'), ('PREPARING', 'Preparing'), ('READY', 'Ready to Serve'), ('SERVED', 'Served'), ('COMPLETED', 'Completed'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled'), ('REJECTED', 'Rejected')], default='ORDER_TAKEN', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='restaurants.table'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('ORDERED', 'Ordered'), ('AWAITING', 'Awaiting'), ('PREPARING', 'Preparing'), ('READY', 'Ready'), ('SERVED', 'Served'), ('CANCELLED', 'Cancelled'), ('REJECTED', 'Rejected')], default='ORDERED', max_length=20),
        ),
    ]
