# Generated by Django 4.2.30 on 2026-04-11 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_order_order_type_orderitem_rejection_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('CARD', 'Card'), ('UPI', 'UPI'), ('NET_BANKING', 'Net Banking'), ('EXTERNAL', 'External/Outside')], default='EXTERNAL', max_length=20),
        ),
    ]
