# Generated by Django 4.2.27 on 2026-04-11 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
        ('restaurants', '0006_alter_invoice_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='stores.store'),
        ),
        migrations.AddField(
            model_name='order',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='stores.store'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='stores.store'),
        ),
        migrations.AddField(
            model_name='table',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='stores.store'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('DINE_IN', 'Dine-in'), ('TAKE_AWAY', 'Parcel')], default='DINE_IN', max_length=20),
        ),
        migrations.AlterField(
            model_name='table',
            name='number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='table',
            unique_together={('number', 'store')},
        ),
    ]
