# Generated by Django 4.2.30 on 2026-04-11 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0007_invoice_store_order_store_reservation_store_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='shape',
            field=models.CharField(choices=[('RECT', 'Rectangle'), ('CIRCLE', 'Circle')], default='RECT', max_length=10),
        ),
    ]
