# Generated by Django 4.2.27 on 2026-04-11 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0009_alter_table_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_mobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('ORDER_TAKEN', 'Order Taken'), ('AWAITING', 'Awaiting'), ('PREPARING', 'Preparing'), ('READY', 'Ready to Serve'), ('SERVED', 'Served'), ('COMPLETED', 'Completed'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled'), ('REJECTED', 'Rejected'), ('RETURNED', 'Returned (Loss)')], default='ORDER_TAKEN', max_length=20),
        ),
    ]
