# Generated by Django 4.2.27 on 2026-04-18 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_create_default_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='is_kitchen_step_enabled',
            field=models.BooleanField(default=True, help_text='If disabled, orders advance to Preparing status immediately after KOT creation and skip the Kitchen Display step.'),
        ),
    ]
