# Generated by Django 4.2.27 on 2026-04-19 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_store_is_kitchen_step_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='is_take_away_enabled',
            field=models.BooleanField(default=True, help_text='Enable or disable the Parcel (Take Away) order feature for this store.'),
        ),
    ]
