# Generated by Django 4.2.30 on 2026-04-19 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_store_is_take_away_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='is_reservations_enabled',
            field=models.BooleanField(default=True, help_text='Enable or disable the Restaurant Reservations feature for this store.'),
        ),
    ]
