# Generated by Django 4.2.27 on 2026-04-19 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0005_store_is_reservations_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='thermal_printer_size',
            field=models.CharField(choices=[('2_INCH', '2 Inch'), ('3_INCH', '3 Inch')], default='3_INCH', help_text='Size of the thermal printer used for invoices (2 inch or 3 inch).', max_length=10),
        ),
    ]
