# Generated by Django 4.2.27 on 2026-04-19 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0006_store_thermal_printer_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='fssai_lic_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='FSSAI License No.'),
        ),
        migrations.AddField(
            model_name='store',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
