# Generated by Django 4.2.30 on 2026-04-29 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0007_store_fssai_lic_no_store_location_store_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='thermal_printer_name',
            field=models.CharField(blank=True, help_text='Name of the thermal printer (e.g. system name)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='thermal_printer_product_id',
            field=models.CharField(blank=True, help_text='USB Product ID of the printer', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='thermal_printer_vendor_id',
            field=models.CharField(blank=True, help_text='USB Vendor ID of the printer', max_length=20, null=True),
        ),
    ]
