# Generated by Django 4.2.27 on 2026-04-10 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_add_users', 'Can add new users to the system')]},
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
