# Generated by Django 4.2.27 on 2026-04-11 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options_remove_user_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_add_users', 'Can add new users to the system'), ('manage_table_layout_access', 'Can manage table layout'), ('view_table_layout_access', 'Can view table layout')]},
        ),
    ]
