# Generated by Django 4.2.30 on 2026-04-18 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0006_alter_user_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_key', models.CharField(max_length=100)),
                ('is_enabled', models.BooleanField(default=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_permissions', to='auth.group')),
            ],
            options={
                'verbose_name': 'Menu Permission',
                'verbose_name_plural': 'Menu Permissions',
                'unique_together': {('group', 'menu_key')},
            },
        ),
    ]
