# Generated by Django 4.2.30 on 2026-04-18 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_menupermission'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MenuPermission',
        ),
    ]
