# Generated by Django 4.2.30 on 2026-04-18 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_delete_menupermission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_add_users', 'Can add new users to the system'), ('manage_table_layout_access', 'Can manage table layout'), ('view_table_layout_access', 'Can view table layout'), ('access_to_update_table_status', 'Can update table status'), ('access_to_take_order', 'Can take restaurant orders'), ('access_to_view_kitchen_display', 'Can view kitchen display'), ('access_to_manage_kitchen_queue', 'Can manage kitchen queue'), ('access_to_payment_management', 'Can manage payment and billing'), ('access_to_delete_order', 'Can delete orders'), ('view_reports', 'Can view analytics and reports')]},
        ),
    ]
