# Generated by Django 4.2.30 on 2026-04-19 09:29

from django.db import migrations

def grant_dashboard_permission(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')
    
    try:
        dashboard_perm = Permission.objects.get(codename='access_to_dashboard')
        # Grant to SUPER_ADMIN, ADMIN, MANAGER by default
        target_groups = ['SUPER_ADMIN', 'ADMIN', 'MANAGER']
        for group_name in target_groups:
            group, created = Group.objects.get_or_create(name=group_name)
            group.permissions.add(dashboard_perm)
    except Permission.DoesNotExist:
        # Permission might not be created yet in the same transaction if we are not careful
        # but Django handles this usually.
        pass

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_add_users', 'Can add new users to the system'), ('manage_table_layout_access', 'Can manage table layout'), ('view_table_layout_access', 'Can view table layout'), ('access_to_update_table_status', 'Can update table status'), ('access_to_take_order', 'Can take restaurant orders'), ('access_to_view_kitchen_display', 'Can view kitchen display'), ('access_to_manage_kitchen_queue', 'Can manage kitchen queue'), ('access_to_payment_management', 'Can manage payment and billing'), ('access_to_delete_order', 'Can delete orders'), ('view_reports', 'Can view analytics and reports'), ('access_to_dashboard', 'Can view dashboard')]},
        ),
        migrations.RunPython(grant_dashboard_permission),
    ]
