# Generated by Django 4.2.27 on 2026-04-11 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaxConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default Tax Configuration', max_length=100)),
                ('tax_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('tax_type', models.CharField(choices=[('INCLUSIVE', 'Inclusive'), ('EXCLUSIVE', 'Exclusive'), ('EXEMPTED', 'Exempted')], default='EXCLUSIVE', max_length=20)),
                ('is_gst_enabled', models.BooleanField(default=False)),
                ('cgst_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('sgst_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('igst_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('is_cess_enabled', models.BooleanField(default=False)),
                ('cess_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tax Configuration',
                'verbose_name_plural': 'Tax Configurations',
            },
        ),
    ]
