# Generated by Django 4.2.27 on 2026-04-11 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_taxconfiguration_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxconfiguration',
            name='tax_percentage',
        ),
    ]
